name: CIlocal

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    #defaults:
    #  run:
    #    shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - conda-env: base
            python-version: 3.9
            label: CI Local
            runs-on: self-hosted
    env:
        CONDA: /psi/ghaconda

    name: "🐍 ${{ matrix.cfg.python-version }} • ${{ matrix.cfg.label }}"
    runs-on: ${{ matrix.cfg.runs-on }}

    steps:
    - uses: actions/checkout@v2

    - name: Create Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: qcbase
        environment-file: devtools/conda-envs/${{ matrix.cfg.conda-env }}.yaml
        python-version: ${{ matrix.cfg.python-version }}
        auto-activate-base: false
        remove-profiles: true

    - name: Environment Information
      run: |
        conda info
        conda list --show-channel-urls

    - name: Install QCDB
      shell: bash -l {0}
      run: |
        python -m pip install . --no-deps --no-use-pep517

    - name: PyTest
      shell: bash -l {0}
      run: |
        export PATH=/psi/gits/hrw-ddd-main/objdir39d41/stage/bin:$PATH  # psi4 executable
        export PYTHONPATH=/psi/gits/hrw-ddd-main/objdir39d41/stage/lib//:$PYTHONPATH  # psi4 pymodule
        export PATH=/psi/gits/gamess:$PATH  # gamess script
        export PATH=/psi/gits/nwchem/bin/LINUX64:$PATH  # nwchem exe
        export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH  # nwchem pylink
        export PATH=/psi/gits/cfour-public/bin:$PATH  # cfour exe
        pytest -rws -v --cov=qcdb --color=yes --cov-report=xml -k test_tu qcdb/

    - name: CodeCov
      uses: codecov/codecov-action@v1

